# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: 'latest'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: mv bookstore-api.py app.py
      displayName: 'changing the file name'
    - script: docker build -t bookstoreapi:latest .
      displayName: 'docker build'
    - script: docker images
      displayName: 'docker images'
    
    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'bookstore'
        azureContainerRegistry: '{"loginServer":"emineacr.azurecr.io", "id" : "/subscriptions/4182b63f-bfaa-4c6b-a529-155e10b3a804/resourceGroups/learning/providers/Microsoft.ContainerRegistry/registries/emineacr"}'
        dockerComposeFile: '**/docker-compose.yml'
        projectName: 'bookstoreapi'
        action: 'Push services'
        additionalImageTags: 'bookstoreapi'
        includeLatestTag: true
    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'bookstore'
        azureContainerRegistry: '{"loginServer":"emineacr.azurecr.io", "id" : "/subscriptions/4182b63f-bfaa-4c6b-a529-155e10b3a804/resourceGroups/learning/providers/Microsoft.ContainerRegistry/registries/emineacr"}'
        dockerComposeFile: '**/docker-compose.yml'
        projectName: 'bookstoreapi'
        action: 'Run a Docker Compose command'
        dockerComposeCommand: 'up'
    
    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'bookstore'
        azureContainerRegistry: '{"loginServer":"emineacr.azurecr.io", "id" : "/subscriptions/4182b63f-bfaa-4c6b-a529-155e10b3a804/resourceGroups/learning/providers/Microsoft.ContainerRegistry/registries/emineacr"}'
        dockerComposeFile: '**/docker-compose.yml'
        projectName: 'bookstoreapi'
        action: 'Combine configuration'
        outputDockerComposeFile: '$(Build.StagingDirectory)/docker-compose.yml'
    
    - script: cat $(Build.StagingDirectory)/docker-compose.yml
      displayName: 'config file display'

