# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: mv bookstore-api.py app.py
      displayName: 'changing the file name'
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)

- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'Azure subscription 1(4182b63f-bfaa-4c6b-a529-155e10b3a804)'
    azureContainerRegistry: '{"loginServer":"emineacr.azurecr.io", "id" : "/subscriptions/4182b63f-bfaa-4c6b-a529-155e10b3a804/resourceGroups/learning/providers/Microsoft.ContainerRegistry/registries/emineacr"}'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'up'